// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new2addFKDispathandDestinStationtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new2addFKDispathandDestinStationtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201611280806466_new 2 add FK Dispath and Dest in Stationtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
