// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class type_NumberOfTrain_change2string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(type_NumberOfTrain_change2string));
        
        string IMigrationMetadata.Id
        {
            get { return "201611221209166_ type_NumberOfTrain_change2string "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
