// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RegulatoryShedulesTableNumberOfTrainChangetypeuint2int : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegulatoryShedulesTableNumberOfTrainChangetypeuint2int));
        
        string IMigrationMetadata.Id
        {
            get { return "201611170332050_RegulatoryShedules Table NumberOfTrain Change type uint2int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
